title: My Blog
description: Personal blog and Qt learning
theme: just-the-docs

includes_dir: "."

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
    values:
      layout: "default"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

compress_html:
  ignore:
    envs: all

mermaid:
  version: "11.3.0"

